name: NanaHopper
version: '${version}'
description: A modern Minecraft plugin supporting Minecraft 1.21+
author: Block_Bring
authors: [ Block_Bring ]
api-version: 1.21
main: top.imbring.nanaHopper.NanaHopper
folia-supported: true

commands:
  hopper:
    description: Manage hoppers taken over by NanaHopper.
    usage: /hopper <claim|release|speed [+/-value|reset]>
    permission: nanahopper.command.hopper

permissions:
  nanahopper.command.hopper:
    description: Allows using the /hopper command.
    default: op
